import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

/**
 * 
 * @author Ian Bryan
 * 
 *~~~~DESCRIPTION AND FUNCTIONALITY~~~~~
 * The second index generated by the split() method takes the i'th position in theDenoms[].
 * Two temporary variables checkNumerator and checkDenom
 * take the value of the i'th element of the numerator and denominator arrays
 * A nested for loop checks 3 things:
 * 1) Boolean array fractionIndexed (all elements start as 'false') is queried for if not true. 
 * When queried, boolean is true and thus the index value is changed to true. When all numerators and denominators are checked,
 * all indices will be true, and the loop will stop. 
 * 2) checkNumerator (a local variable) is assigned the i'th index of theNumerators[]
 * then it is compared against all indices of theNumerators[].
 * The same is done for checkDenom with theDenoms[].
 * 3) The above conditions will generate a +1 increment in dupeCounter (a counter for duplicate fractions meaning that
 * the numerator and denominator of the arrays matched at least one numerator and denominator at the same time
 * in their respective array indices. 
 * For any fraction with no matching numerator/denominator sequence produces a +1 counter for dupeCounter.
 * The dupeCounter is set to 0 at the end of the first for-loop (the outside one)
 * 
 * ~~~~COMMENT~~~~~
 * I tried to set the size of the listOfFractions to the lineCounter using the following code:
 * 
 * I found this on StackOverflow and read more on what constitutes a "new line" 
 * and this did end up producing the correct line number
 * but when I compiled the code and ran it, it produced 31 "nulls". 
 * 
 *  public void openTheFile(){
 * 		BufferedReader readFile = new BufferedReader(new FileReader("fractions.txt"));
 *  	int numOfFracts = 0;
 *		while (readFile.readLine() != null) {numOfFracts++;}
 *		readFile.close();
 *
 *		Scanner dataFile = new Scanner("fractions.txt");
 *		String[] listOfFractions = new String[numOfFracts];
 *		while(dataFile.hasNextLine()){
 *			listOfFractions[i] = dataFile.nextLine();
 *		}
 *	}
 */

public class FractionsV1 {

	/*
	 * Data Types [Arrays]
	 * 
	 * String array is declared and will be resized to store the fraction values
	 * Another String array of length 2 used to for containing the numerator/denominator
	 * int arrays for the numerators and denominators once they're split
	 * The boonlean array is used to check if that "card" in the "deck" already exists
	 * */
	String[] listOfFractions = new String[31];
	private String[] splitFractions = new String[2];
	private int[] theNumerators = new int[31];
	private int[] theDenoms = new int[31];
	private boolean[] fractionIndexed = new boolean[31];

	/*
	 * Data Types (primitive)
	 * 
	 * */
	private int lineCounter = 0;
	private int dupeCounter = 0;
	private int checkDenom = 0;
	private int checkNumerator = 0;

	Scanner dataFile = null;

	/*Begin Main*/
	public static void main(String[] args) {

		FractionsV1 fv1 = new FractionsV1();
		fv1.openTheFile();
		fv1.countRowsInFile();
		fv1.splitListOfFractions();
		fv1.compareND();
		fv1.closeTheFile();
	}

	public void openTheFile(){

		try{
			dataFile = new Scanner(new File("fractions.txt"));
		}catch(FileNotFoundException e){
			System.out.println("Program unable to locate file. Check directory and try again");
			System.exit(0);
		}
	}
	
	public void countRowsInFile(){

		for(int a=0;dataFile.hasNextLine();a++){
			listOfFractions[a] = dataFile.nextLine();
			lineCounter++;
		}
	}

	public void splitListOfFractions(){
		for(int b=0;b<lineCounter;b++){
			splitFractions = listOfFractions[b].split("/");
			theNumerators[b] = Integer.parseInt(splitFractions[0]);
			theDenoms[b] = Integer.parseInt(splitFractions[1]);
		}
	}
	public void compareND(){

		for(int i=0;i<lineCounter;i++){
			checkNumerator = theNumerators[i];
			checkDenom = theDenoms[i];

			//nested for-loop
			for(int c=0;c<lineCounter;c++){
				if(!fractionIndexed[c]){
					if(checkDenom == theDenoms[c]){
						if(checkNumerator == theNumerators[c]){
							dupeCounter++;
							fractionIndexed[c] = true; //the fraction already exists in the listOfFractions array
						}//end if block
					}//end if block
				}//end last nested if
			}//end for loop

			if(dupeCounter > 0){
				System.out.println(checkNumerator + "/" + checkDenom + " has a count of " + dupeCounter);
			}
			dupeCounter = 0;
		}
	}

	//close the file for the end of the program
	public void closeTheFile(){dataFile.close();
	}
}